# src/analyzers/domain_analyzer.py
from typing import Dict, List
from src.models.market_metrics import DomainMetrics

# Предопределённые домены – можно вынести в JSON или БД
DOMAIN_MAP = {
    "Backend": [
        "python", "java", "go", "golang", "rust", "c#", "csharp", "php", "ruby", "node.js", "nodejs",
        "django", "flask", "fastapi", "spring", "spring boot", "spring cloud", "express", "express.js",
        "nestjs", "laravel", "symfony", "phoenix framework", "elixir", "erlang", "scala", "kotlin", "ktor",
        "sql", "postgresql", "mysql", "mariadb", "mongodb", "redis", "elasticsearch", "cassandra", "oracle db",
        "ms sql server", "sqlite", "neo4j", "clickhouse", "timescaledb", "dynamodb", "couchdb",
        "rest api", "restful", "graphql", "grpc", "soap", "odata", "openapi", "swagger",
        "docker", "kubernetes", "k8s", "git", "gitlab", "github", "bitbucket",
        "rabbitmq", "kafka", "apache kafka", "kafka streams", "celery", "zeromq",
        "nginx", "apache", "haproxy", "envoy", "istio", "linkerd", "service mesh",
        "microservices", "микросервисная архитектура", "ddd", "domain-driven design",
        "orm", "prisma", "sequelize", "hibernate", "entity framework", "jpa", "sqlalchemy",
        "jdbc", "odbc", "ado.net",
        "json", "xml", "yaml", "protobuf", "raml",
        "oauth 2.0", "oidc", "jwt", "auth0", "identity server", "keycloak",
        "cloud", "aws", "azure", "gcp", "yandex cloud", "heroku", "digitalocean",
        "serverless", "lambda", "cloud functions", "cloudformation", "terraform",
        "ci/cd", "jenkins", "teamcity", "travis ci", "gitlab ci/cd", "argo cd", "spinnaker",
        "vault", "consul", "zookeeper", "etcd",
        "caching", "memcached", "redis stack",
        "saga", "outbox pattern", "cqrs", "event sourcing",
        "высокая доступность", "репликация", "шардирование", "партиционирование",
        "оптимизация sql-запросов", "sql оптимизация", "нормализация бд", "документоориентированные бд",
        "acid", "cap theorem", "транзакции",
    ],
    "Frontend": [
        "javascript", "typescript", "js", "ts", "react", "react.js", "vue", "vue.js", "angular", "angular.js",
        "next.js", "nextjs", "nuxt.js", "nuxtjs", "gatsby", "svelte", "sveltekit", "remix", "redwoodjs",
        "html", "html5", "css", "css3", "scss", "sass", "less", "tailwind", "tailwind css", "bootstrap",
        "material-ui", "mui", "ant design", "chakra ui", "headless ui",
        "webpack", "vite", "babel", "esbuild", "rollup", "parcel", "turborepo",
        "redux", "redux toolkit", "mobx", "zustand", "recoil", "flux", "vuex", "pinia",
        "graphql", "apollo", "relay", "urql", "graphql federation",
        "rest api", "axios", "fetch", "swr", "tanstack query", "react query",
        "websockets", "socket.io", "signalr", "webrtc", "webtransport",
        "pwa", "service workers", "workbox", "spa", "ssr", "ssg", "isr",
        "jamstack", "headless cms", "strapi", "contentful", "sanity", "directus",
        "testing", "jest", "cypress", "playwright", "mocha", "vitest", "react testing library",
        "storybook", "chromatic", "percy",
        "figma", "sketch", "adobe xd", "balsamiq", "axure", "zeplin", "invision",
        "framer motion", "gsap", "three.js", "webgl", "d3.js", "chart.js", "highcharts",
        "eslint", "prettier", "husky", "lint-staged",
        "адаптивная верстка", "кроссбраузерная верстка", "верстка email", "amp",
        "web vitals", "core web vitals", "lighthouse", "pagespeed insights",
        "seo", "semantic html", "microdata", "json-ld",
    ],
    "Data Science": [
        "python", "r", "sql", "pandas", "numpy", "scipy", "matplotlib", "seaborn", "plotly", "bokeh",
        "scikit-learn", "sklearn", "tensorflow", "pytorch", "keras", "mxnet", "xgboost", "lightgbm", "catboost",
        "machine learning", "машинное обучение", "deep learning", "глубокое обучение",
        "нейронные сети", "neural networks", "cnn", "rnn", "lstm", "gru", "transformer", "attention",
        "nlp", "обработка естественного языка", "spacy", "nltk", "bert", "gpt", "llm", "большие языковые модели",
        "computer vision", "компьютерное зрение", "opencv", "yolo", "resnet", "vgg", "mediapipe",
        "data science", "data analysis", "data mining", "data visualization", "визуализация данных",
        "статистика", "statistics", "теория вероятностей", "матстатистика", "байесовский вывод",
        "ab testing", "a/b тестирование", "проверка гипотез", "доверительные интервалы",
        "big data", "spark", "pyspark", "hadoop", "hive", "presto", "trino", "flink", "databricks",
        "airflow", "apache airflow", "mlflow", "kubeflow", "prefect", "dagster",
        "tableau", "power bi", "looker", "superset", "redash", "metabase",
        "jupyter", "jupyterhub", "streamlit", "dash", "shiny",
        "feature engineering", "feature selection", "feature store", "data preprocessing",
        "time series", "временные ряды", "prophet", "arima", "sas", "matlab",
        "recommender systems", "рекомендательные системы", "коллаборативная фильтрация",
        "anomaly detection", "поиск аномалий", "outlier detection",
        "bayesian", "байесовские методы", "mcmc", "вариационный вывод", "pymc", "stan",
        "graph analytics", "networkx", "neo4j", "graph neural networks", "gnn",
        "mlops", "model serving", "model monitoring", "drift detection",
        "responsible ai", "этичный ии", "fairness", "bias mitigation", "explainable ai",
        "интерпретируемость", "shap", "lime", "eli5",
        "data engineering", "etl", "elt", "dbt", "data warehouse", "data lake", "data vault",
        "dwh", "greenplum", "arenadata db", "vertica", "snowflake", "bigquery", "redshift",
        "синтетические данные", "data augmentation", "smote",
        "генеративные модели", "gan", "vae", "stable diffusion", "dall-e",
        "reinforcement learning", "обучение с подкреплением", "rl", "q-learning", "policy gradient",
        "мультиагентные системы", "multi-agent", "агентное моделирование",
        "федеративное обучение", "federated learning", "дифференциальная приватность",
        "adversarial attacks", "adversarial robustness", "защита моделей",
        "few-shot learning", "zero-shot learning", "meta-learning",
        "fine-tuning", "дообучение", "transfer learning", "перенос обучения",
        "prompt engineering", "инженерия промптов", "langchain", "rag", "lora", "peft",
        "function calling", "structured outputs", "reasoning", "agents",
        "llm-as-a-judge", "human evaluation", "benchmarking", "бенчмаркинг",
        "текстовая аналитика", "text mining", "sentiment analysis", "topic modeling",
        "network analysis", "социальные сети", "графовые алгоритмы",
        "криптография", "гомоморфное шифрование", "конфиденциальные вычисления",
    ],
    "DevOps & Infrastructure": [
        "linux", "unix", "bash", "shell", "powershell", "cmd", "terminal",
        "docker", "kubernetes", "k8s", "openshift", "rancher", "containerd", "podman",
        "jenkins", "gitlab ci", "github actions", "circleci", "travis ci", "teamcity", "bamboo",
        "terraform", "ansible", "chef", "puppet", "saltstack", "vagrant", "packer",
        "prometheus", "grafana", "victoriametrics", "thanos", "cortex", "loki", "elk stack",
        "elasticsearch", "logstash", "kibana", "fluentd", "datadog", "new relic", "splunk",
        "aws", "amazon web services", "azure", "microsoft azure", "gcp", "google cloud platform",
        "yandex cloud", "alibaba cloud", "ibm cloud", "oracle cloud",
        "nginx", "apache", "haproxy", "traefik", "caddy", "envoy",
        "ci/cd", "continuous integration", "continuous delivery", "continuous deployment",
        "git", "github", "gitlab", "bitbucket", "azure devops", "svn", "mercurial",
        "infrastructure as code", "iac", "cloudformation", "azure resource manager", "bicep",
        "configuration management", "управление конфигурациями",
        "service mesh", "istio", "linkerd", "consul connect", "kuma",
        "secrets management", "vault", "sealed secrets", "sops",
        "backup", "disaster recovery", "high availability", "site reliability engineering", "sre",
        "chaos engineering", "gremlin", "chaos mesh",
        "networking", "сети", "tcp/ip", "dns", "http/2", "http/3", "websockets", "grpc",
        "vpn", "firewall", "load balancer", "cdn", "cloudflare", "akamai", "fastly",
        "virtualization", "vmware", "hyper-v", "kvm", "xen", "virtualbox",
        "storage", "nfs", "ceph", "glusterfs", "minio", "s3", "azure blob", "google cloud storage",
        "caching", "varnish", "squid", "redis", "memcached",
        "web servers", "apache", "nginx", "iis", "lighttpd",
        "monitoring", "наблюдение", "alerting", "pagerduty", "opsgenie", "victorops",
        "cost optimization", "finops", "cloud financial management",
        "greenplum", "clickhouse", "big data infrastructure", "hadoop", "spark on k8s",
    ],
    "Mobile Development": [
        "android", "ios", "kotlin", "swift", "swiftui", "objective-c", "java",
        "flutter", "dart", "react native", "xamarin", "maui", "ionic", "cordova", "phonegap",
        "mobile", "мобильная разработка", "разработка мобильных приложений",
        "android sdk", "android studio", "xcode", "cocoapods", "spm", "gradle",
        "google play console", "app store connect", "testflight", "firebase test lab",
        "mobile testing", "appium", "detox", "espresso", "xcuitest", "robolectric",
        "push notifications", "fcm", "apns", "onesignal", "firebase cloud messaging",
        "mobile analytics", "firebase analytics", "google analytics for mobile", "mixpanel", "amplitude",
        "mobile security", "mobile devops", "fastlane", "bitrise", "codemagic",
        "core data", "realm", "room", "sqlite on mobile",
        "location services", "maps", "geofencing", "beacons", "bluetooth", "nfc",
        "camera", "augmented reality", "arcore", "arkit", "vuforia",
        "mobile performance", "profilers", "memory optimization", "battery optimization",
        "mobile architecture", "mvvm", "mvp", "viper", "clean architecture", "bloc", "riverpod",
        "instant apps", "app bundles", "dynamic feature modules",
        "mobile games", "unity", "unreal engine", "cocos2d", "spritekit",
        "pwa for mobile", "trusted web activity",
    ],
    "QA / Testing": [
        "тестирование по", "тестирование", "qa", "quality assurance", "testing",
        "ручное тестирование", "manual testing", "автоматизированное тестирование", "automation testing",
        "selenium", "webdriver", "cypress", "playwright", "puppeteer", "testcafe", "nightwatch",
        "jest", "mocha", "jasmine", "karma", "vitest", "ava", "tape",
        "pytest", "unittest", "nose", "behave", "robot framework", "cucumber", "gherkin",
        "junit", "testng", "nunit", "xunit", "ms test",
        "appium", "detox", "espresso", "xcuitest", "calabash",
        "api testing", "postman", "soapui", "rest assured", "karate", "jmeter", "k6", "gatling",
        "performance testing", "нагрузочное тестирование", "stress testing", "soak testing",
        "security testing", "penetration testing", "owasp", "burp suite", "zap",
        "accessibility testing", "axe", "wave", "lighthouse accessibility",
        "visual regression testing", "percy", "applitools", "chromatic", "backstopjs",
        "contract testing", "pact", "spring cloud contract",
        "mutation testing", "stryker", "pitest",
        "test management", "testrail", "zephyr", "xray", "qtest", "practitest",
        "bug tracking", "jira", "youtrack", "redmine", "bugzilla", "mantis",
        "tdd", "bdd", "atdd", "shift-left testing", "continuous testing",
        "test automation framework", "data driven testing", "keyword driven testing", "page object model",
        "mobile testing", "cross browser testing", "browserstack", "saucelabs", "lambdatest",
        "тест-дизайн", "test design", "чек-листы", "test cases", "баг-репорты",
        "qa метрики", "test coverage", "defect density", "defect leakage",
        "статическое тестирование", "code review", "статический анализ кода", "sonarqube",
        "chaos testing", "gremlin", "chaos monkey",
    ],
    "1C & ERP": [
        "1с", "1c", "1с предприятие", "1с 8", "1с 8.3", "1с программирование",
        "1c erp", "1с бухгалтерия", "1с зарплата и управление персоналом", "1с зуп",
        "1с документооборот", "1с розница", "1с управление производственным предприятием", "1с ут",
        "1с комплексная автоматизация", "1с унф", "1с бит", "1с бухгалтерия государственного учреждения",
        "администрирование 1с", "интеграция 1с с другими системами", "обмен данными 1с",
        "erp", "enterprise resource planning", "sap", "oracle erp", "microsoft dynamics", "dynamics 365",
        "galaxy", "парус", "турбо", "компас", "it enterprise", "infor", "ifs", "epicor",
        "crm", "salesforce", "microsoft dynamics crm", "creatio", "bpm online", "amo crm", "bitrix24",
        "управление предприятием", "автоматизация бизнес-процессов", "внедрение erp", "моделирование бизнес-процессов",
        "бизнес-анализ", "системный анализ", "разработка бизнес-требований", "техническое задание",
        "bpmn", "idef0", "uml", "arisl", "business studio", "togaf", "archimate",
        "управление проектами", "project management", "agile", "scrum", "kanban", "waterfall",
        "pmbok", "prince2", "pmp", "ipma", "ms project", "jira", "confluence", "trello", "asana",
        "управление рисками", "риск-менеджмент", "управление качеством", "tqm", "six sigma", "lean",
        "itil", "itsm", "cobit", "управление ит-услугами", "управление ит-инфраструктурой",
        "бюджетирование", "управленческий учёт", "бухгалтерский учёт", "налоговый учёт",
        "финансовый анализ", "power pivot", "power query", "excel", "google sheets",
    ],
    "AI/ML Research & Advanced": [
        "research", "исследования", "r&d", "научные исследования", "machine learning research",
        "deep learning research", "new architectures", "новые архитектуры", "нейросетевые инновации",
        "reinforcement learning", "rl", "deep rl", "q-learning", "policy gradient", "actor-critic",
        "мультиагентные системы", "multi-agent rl", "marl", "агентное моделирование",
        "generative models", "gan", "vae", "normalizing flows", "diffusion models", "диффузионные модели",
        "graph neural networks", "gnn", "graph attention networks", "node embedding", "graph isomorphism",
        "bayesian deep learning", "гауссовские процессы", "нейробайесовские методы", "вариационный вывод",
        "federated learning", "федеративное обучение", "privacy-preserving ml", "дифференциальная приватность",
        "adversarial robustness", "adversarial training", "robust optimization", "certified defenses",
        "interpretability", "explainable ai", "xai", "feature attribution", "counterfactual explanations",
        "few-shot learning", "zero-shot learning", "meta-learning", "learning to learn",
        "neural architecture search", "nas", "automl", "hyperparameter optimization", "optuna", "hyperopt",
        "causal inference", "causality", "do-calculus", "structural causal models", "instrumental variables",
        "time series forecasting", "state space models", "prophet", "arima", "var", "deepar", "tft",
        "natural language processing", "transformers", "attention is all you need", "bert", "gpt", "t5",
        "llama", "mistral", "falcon", "mpt", "large language models", "scaling laws", "mixture of experts",
        "prompt engineering", "chain of thought", "tree of thoughts", "react prompting", "function calling",
        "retrieval augmented generation", "rag", "vector databases", "pinecone", "weaviate", "qdrant",
        "fine-tuning llm", "lora", "qlora", "peft", "parameter-efficient fine-tuning",
        "multimodal learning", "мультимодальные модели", "clip", "flamingo", "blip", "imagebind",
        "embodied ai", "вещественный ии", "robotics", "ros", "simulation", "isaac sim", "gazebo",
        "quantum machine learning", "qml", "tensorflow quantum", "pennylane", "qiskit",
        "computational neuroscience", "spiking neural networks", "neuromorphic computing",
        "ethical ai", "ai safety", "alignment", "superalignment", "responsible ai", "fairness", "bias",
        "ai governance", "regulatory compliance", "eu ai act", "gdpr for ai",
    ],
    "Cybersecurity": [
        "кибербезопасность", "cybersecurity", "information security", "информационная безопасность",
        "network security", "сетевая безопасность", "firewall", "ids/ips", "vpn", "zero trust",
        "application security", "appsec", "owasp", "sast", "dast", "iast", "rasp",
        "penetration testing", "pentest", "ethical hacking", "red team", "blue team", "purple team",
        "vulnerability assessment", "threat modeling", "моделирование угроз", "оценка уязвимостей",
        "secure coding", "security champions", "devsecops", "security as code", "policy as code",
        "identity and access management", "iam", "oauth", "saml", "oidc", "ldap", "active directory",
        "privileged access management", "pam", "multi-factor authentication", "mfa", "fido2",
        "cryptography", "криптография", "pki", "tls", "ssl", "aes", "rsa", "ecc", "quantum cryptography",
        "data protection", "dlp", "data masking", "tokenization", "encryption at rest", "encryption in transit",
        "cloud security", "aws security", "azure security", "gcp security", "casb", "cspm", "cwpp",
        "container security", "kubernetes security", "image scanning", "trivy", "snyk", "aqua", "prisma cloud",
        "endpoint security", "edr", "xdr", "antivirus", "crowdstrike", "sentinelone", "microsoft defender",
        "siem", "splunk", "qradar", "azure sentinel", "chronicle", "elk for security", "wazuh",
        "incident response", "forensics", "digital forensics", "sans", "nist", "iso 27001", "pci dss",
        "compliance", "аудит безопасности", "security assessment", "управление рисками ии", "ai security",
        "adversarial machine learning", "model poisoning", "membership inference", "model inversion",
        "privacy", "gdpr", "ccpa", "federated learning", "дифференциальная приватность", "гомоморфное шифрование",
    ],
    "Game Development": [
        "unity", "unreal engine", "unreal engine 5", "ue5", "godot", "cryengine", "amazon lumberyard",
        "game design", "level design", "game mechanics", "gameplay programming", "game physics",
        "c#", "c++", "blueprints", "visual scripting", "shader graph", "hlsl", "glsl", "cg",
        "2d", "3d", "animation", "rigging", "motion capture", "character design", "environment art",
        "vfx", "particle systems", "niagara", "cascade", "post-processing", "ray tracing",
        "virtual reality", "vr", "ar", "augmented reality", "mixed reality", "openxr", "steamvr", "oculus",
        "mobile games", "ios games", "android games", "play store", "app store", "google play games",
        "multiplayer", "networking for games", "photon", "mirror", "unity netcode", "unreal multiplayer",
        "game ai", "behavior trees", "finite state machines", "pathfinding", "navmesh", "a*",
        "game optimization", "performance profiling", "memory management", "loading times",
        "game analytics", "unity analytics", "game sparks", "playfab", "firebase for games",
        "monetization", "in-app purchases", "ads", "advertisement", "unity ads", "admob",
        "game testing", "qa for games", "playtesting", "bug reporting", "compatibility testing",
        "game production", "game project management", "agile for games", "scrum for games",
        "sound design", "fmod", "wwise", "audio implementation", "game audio",
    ],
    "Embedded & Systems": [
        "c", "c++", "rust", "embedded c", "embedded c++", "assembly", "arm", "avr", "pic", "msp430",
        "arduino", "raspberry pi", "esp32", "stm32", "nrf52", "microcontroller", "микроконтроллер",
        "rtos", "freertos", "zephyr", "threadx", "vxworks", "qnx", "embedded linux", "buildroot", "yocto",
        "device drivers", "разработка драйверов", "linux kernel", "kernel module", "bios", "uefi", "bare metal",
        "fpga", "verilog", "vhdl", "xilinx", "altera", "intel fpga", "lattice", "asic", "soc", "system on chip",
        "dsp", "digital signal processing", "matlab", "simulink", "labview", "signal processing",
        "can bus", "modbus", "profibus", "ethernet/ip", "profinet", "mqtt", "coap", "opc ua", "industrial ethernet",
        "plc", "программирование плк", "siemens", "rockwell", "beckhoff", "codesys", "iec 61131-3",
        "scada", "wincc", "ignition", "vt scada", "промышленная автоматизация", "industry 4.0",
        "robotics", "ros", "ros2", "robotics operating system", "moveit", "gazebo", "robot programming",
        "control systems", "pid", "mpc", "lqr", "kalman filter", "automatic control theory",
        "hardware", "аппаратное обеспечение", "pcb design", "altium", "eagle", "kicad", "schematic", "layout",
        "testing", "oscilloscope", "logic analyzer", "jtag", "swd", "debugging",
        "firmware", "прошивка", "bootloader", "ota updates", "secure boot", "trustzone", "tpm",
        "low power", "energy harvesting", "battery management", "power management ic",
        "iot", "internet of things", "интернет вещей", "aws iot", "azure iot", "google cloud iot",
        "lora", "lorawan", "sigfox", "nb-iot", "zigbee", "zwave", "bluetooth le", "ble", "wifi", "nfc", "rfid",
        "сенсоры", "акселерометр", "гироскоп", "магнитометр", "датчики температуры", "датчики давления",
    ],
    "GIS & Spatial": [
        "gis", "геоинформационные системы", "гис", "arcgis", "qgis", "mapinfo", "postgis", "geoserver",
        "openlayers", "leaflet", "mapbox", "google maps api", "yandex maps api", "2gis api",
        "remote sensing", "ддз", "дистанционное зондирование", "спутниковые снимки", "landsat", "sentinel",
        "photogrammetry", "фотограмметрия", "lidar", "las", "dem", "dtm", "dsm",
        "spatial analysis", "пространственный анализ", "geostatistics", "kriging", "interpolation",
        "spatial databases", "пространственные базы данных", "geopandas", "rasterio", "xarray", "gdal",
        "geocoding", "геокодирование", "reverse geocoding", "routing", "маршрутизация", "osrm", "graphhopper",
        "cad", "autocad", "civil 3d", "microstation", "revit", "bim", "building information modeling",
        "surveying", "геодезия", "gnss", "gps", "glonass", "total station", "laser scanning",
        "3d modelling", "sketchup", "blender", "3ds max", "cityengine", "cesium", "terrain",
        "web mapping", "web gis", "wms", "wfs", "wmts", "ogc standards",
        "python for gis", "arcpy", "pyqgis", "geemap", "google earth engine",
        "visualization", "cartography", "картография", "тематическое картографирование", "map design",
    ],
    "Soft Skills & Management": [
        "коммуникация", "работа в команде", "командная работа", "эффективное общение", "коллаборация",
        "soft skills", "гибкие навыки", "межличностные навыки", "лидерство", "управление людьми",
        "учет ролевых особенностей", "межпрофессиональная коммуникация", "кросс-функциональное взаимодействие",
        "управление проектами", "project management", "agile", "scrum", "kanban", "waterfall",
        "постановка задач", "task management", "делегирование", "приоритизация", "управление временем",
        "управление рисками", "управление качеством", "управление изменениями", "change management",
        "системное мышление", "критическое мышление", "аналитическое мышление", "стратегическое мышление",
        "принятие решений", "решение проблем", "problem solving", "креативность", "инновационность",
        "клиентоориентированность", "ориентация на результат", "проактивность", "ответственность",
        "наставничество", "менторство", "коучинг", "развитие персонала", "управление талантами",
        "презентационные навыки", "публичные выступления", "навыки переговоров", "ведение переговоров",
        "эмоциональный интеллект", "eq", "стрессоустойчивость", "конфликтология", "разрешение конфликтов",
        "этика", "профессиональная этика", "корпоративная культура", "diversity and inclusion",
        "ведение документации", "техническая документация", "technical writing", "написание тз",
        "бизнес-анализ", "сбор требований", "интервьюирование", "фасилитация", "модерация встреч",
        "знание английского", "english", "технический английский", "деловая переписка", "международная коммуникация",
    ],
}

class DomainAnalyzer:
    def __init__(self, domain_map: Dict[str, List[str]] = None):
        self.domain_map = domain_map or DOMAIN_MAP

    def compute_domain_coverage(self, user_skills: List[str]) -> Dict[str, DomainMetrics]:
        user_set = set(skill.lower().strip() for skill in user_skills)
        result = {}

        for domain_name, skills in self.domain_map.items():
            dm = DomainMetrics(domain=domain_name, required_skills=skills)
            dm.compute_coverage(user_set)
            # importance можно сделать динамическим из рыночных данных, пока 1.0
            dm.importance = 1.0
            result[domain_name] = dm

        return result